import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// Register PWA service worker (generated by vite-plugin-pwa at build time)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', async () => {
    try {
      // @ts-expect-error virtual module resolved at build time
      const { registerSW } = await import('virtual:pwa-register');
      registerSW({ immediate: true });
    } catch {
      // dev mode — no SW
    }
  });
}
